name:                humperdoo
version:             0.1.0.0
github:              "magicloud/humperdoo"
license:             BSD3
author:              "Magicloud"
maintainer:          "magiclouds@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md
- humperdoo.glade

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            None

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/magicloud/humperdoo#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk
- base-unicode-symbols
- text
- directory
- filepath
- haskell-gi-base
- gi-gio
- gi-gdkpixbuf
- process

library:
  source-dirs: src

executables:
  humperdoo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - humperdoo

tests:
  humperdoo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - humperdoo
